- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: " Migrations to memstash"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations > migrations.txt
    date >> migrations.txt
    curl -H "Content-Type: text/plain" \
      -H "token: {{lookup('env', 'MEMSTASH_TOKEN') }}" \
      --request PUT \
      --data "$(cat migrations.txt)" \
      https://api.memstash.io/values/migrations
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present